[project]
name = "flaskr"
version = "1.0.0"
dependencies = [
    "Flask",
    "Flask-SQLAlchemy",
    "gunicorn",
    "psycopg2",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["flaskr"]
